[package]
name = "integer-sum"
version = "0.1.0"
authors = ["iavl <z6521256@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
